src/App.tsx, src/apis/api/firebase.ts, src/apis/api/leagueoflegends.ts, src/apis/api/user.ts, src/components/CardContainer.tsx, src/components/Layout.tsx, src/components/card-actions/JoinBtn.tsx, src/components/errorFallback/NotFound.tsx, src/components/header/UserMenu.tsx, src/index.css, src/pages/leagueoflegends/Card.tsx, src/pages/leagueoflegends/CardDetailContainer.tsx, src/pages/leagueoflegends/CardListContainer.tsx, src/pages/leagueoflegends/CardListFetcher.tsx, src/pages/leagueoflegends/CreateCard.tsx, src/pages/leagueoflegends/EditCard.tsx, src/pages/leagueoflegends/main.tsx, src/pages/mypage/UserInfoContainer.tsx, src/pages/mypage/UserInfoFetcher.tsx, src/pages/register/SetFavGame.tsx, src/store/card-slice.ts, src/store/mypage-slice.ts
add pagination and fix some erros before deploy
- 1 페이지네이션 추가
- 2 404 페이지 추가
- 3 기본 사용자 동작 에러처리
- 4 
=> add pagination and fix some erros before deploy

src/apis/api/user.ts, src/pages/register/GameInput.tsx
=> fix: fix error in register games page

src/components/card-actions/EditCardBtn.tsx
=> fix : eslint error fix

public/firebase-messaging-sw.js, src/assets/Games.data.ts, src/components/Layout.tsx, src/components/header/GameMenu.tsx, src/components/notification/NotiAccordion.tsx, src/components/notification/NotiAccordionDetail.tsx, src/components/notification/Notification.tsx, src/firebase.ts, src/pages/leagueoflegends/CreateCard.tsx
=> Add background notification

.github/workflows/firebase-hosting-merge.yml, .github/workflows/firebase-hosting-pull-request.yml, public/firebase-messaging-sw.js, src/pages/leagueoflegends/CardDetailFetcher.tsx, src/pages/leagueoflegends/MemberSlot.tsx
=> fix: fcm erros #1

.github/workflows/firebase-hosting-merge.yml, .github/workflows/firebase-hosting-pull-request.yml
=> hotfix: github action errors

src/components/Layout.tsx
=> fix: deleteToken before getToken

src/components/Layout.tsx
=> fix: remove deleteToken

public/firebase-messaging-sw.js, src/components/Layout.tsx, src/pages/register/InputOverwatch.tsx
=> chore: delete console.log

src/apis/api/common.ts, src/apis/api/pubg.ts, src/apis/api/user.ts, src/pages/battlegrounds/Card.tsx, src/pages/battlegrounds/MemberSlot.tsx, src/pages/mypage/GameInfo.tsx, src/pages/mypage/Games.tsx, src/pages/mypage/Games/AddGame.tsx, src/pages/mypage/Games/LolInfo.tsx, src/pages/mypage/Games/Nickname.tsx, src/pages/mypage/Games/OverwatchInfo.tsx, src/pages/mypage/Games/PubgInfo.tsx, src/pages/mypage/MyInfo.tsx, src/pages/mypage/UserInfoContainer.tsx, src/pages/mypage/UserInfoFetcher.tsx, src/pages/mypage/data.ts, src/store/mypage-slice.ts
Add information display and update function for each game
=> Add information display and update function for each game

src/apis/api/user.ts, src/assets/Games.data.ts, src/pages/register/Games.tsx
=> hotfix: unable valorant

src/apis/api/user.ts, src/pages/overwatch/Card.tsx, src/pages/overwatch/CreateCard.tsx, src/pages/overwatch/MemberSlot.tsx, src/pages/register/InputLol.tsx, src/pages/register/InputOverwatch.tsx, src/pages/register/InputPubg.tsx
=> fix: overwatch memberinfo update

src/pages/battlegrounds/Card.tsx, src/pages/battlegrounds/CreateCard.tsx, src/pages/landing/Description.tsx, src/pages/landing/Service.tsx, src/pages/leagueoflegends/CreateCard.tsx, src/pages/overwatch/CreateCard.tsx
=> [deploy] update landing and nickname verification logic

src/apis/api/user.ts, src/pages/battlegrounds/MemberSlot.tsx, src/pages/leagueoflegends/MemberSlot.tsx, src/pages/overwatch/MemberSlot.tsx
=> Add evaluation information

src/pages/mypage/Follow.tsx, src/pages/mypage/Games.tsx, src/pages/mypage/Games/AddGame.tsx, src/pages/mypage/Games/LolInfo.tsx, src/pages/mypage/Games/Nickname.tsx, src/pages/mypage/Games/OverwatchInfo.tsx, src/pages/mypage/Games/PubgInfo.tsx, src/pages/mypage/MyInfo.tsx, src/pages/mypage/UserInfoContainer.tsx, src/pages/mypage/index.tsx
=> refactoring mypage

package-lock.json, package.json, src/App.tsx, src/apis/api/admin.ts, src/apis/utils/index.ts, src/pages/login/AdminLogin.tsx, src/pages/login/redirect.tsx, src/store/user-slice.ts
=> Feat : Add Admin Login

src/functions/commons.ts, src/pages/battlegrounds/MemberSlot.tsx, src/pages/leagueoflegends/MemberSlot.tsx, src/pages/login/index.tsx, src/pages/overwatch/MemberSlot.tsx
=> feat : add link to admin login

src/App.tsx, src/hoc/AuthHoc.tsx, src/pages/battlegrounds/index.tsx, src/pages/leagueoflegends/index.tsx, src/pages/overwatch/index.tsx
사용자 별 페이지 접근 제한
- 1  AuthHoc 업데이트
- 2  업데이트한 AuthHoc 적용
=> Feat: Add AuthHoc

src/assets/Games.data.ts, src/components/chat/JoinedPartyList.tsx, src/pages/mypage/Follow.tsx, src/pages/mypage/Games.tsx, src/pages/register/Games.tsx, src/pages/register/InputValorant.tsx, src/pages/register/SetFavGame.tsx, src/store/register-slice.ts
=> Add RiotSignButton on Register

src/pages/register/Games.tsx
=> [deploy] Add vlrt Nickname to redux

src/assets/Terms.data.tsx, src/pages/battlegrounds/CardDetailContainer.tsx, src/pages/leagueoflegends/CardDetailContainer.tsx, src/pages/overwatch/CardDetailContainer.tsx
- add memoization in card detail
=> [deploy] add memoization in card detail

src/pages/register/Games.tsx, src/pages/register/InputValorant.tsx
=> [deploy] call VLRT history API

src/apis/api/pubg.ts, src/pages/battlegrounds/Card.tsx, src/pages/leagueoflegends/Card.tsx, src/pages/overwatch/Card.tsx
- modify pubg platform get api
closes #112
=> modify pubg platform get api

src/assets/Terms.data.tsx, src/components/CardContainer.tsx, src/components/notification/Notification.tsx, src/pages/overwatch/CardDetailContainer.tsx, src/pages/register/Games.tsx, src/pages/register/InputValorant.tsx
- modify pubg platform get api and add React memoization
=> [deploy] modify pubg platform get api and add React memoization

src/apis/api/valorant.ts, src/pages/mypage/RsoCallback.tsx
=> [deploy] Update RSO login 

src/assets/Games.data.ts, src/components/CardContainer.tsx, src/components/chat/JoinedPartyList.tsx, src/pages/battlegrounds/Card.tsx, src/pages/leagueoflegends/Card.tsx, src/pages/mypage/Games.tsx, src/pages/mypage/Games/Nickname.tsx, src/pages/mypage/Games/ValorantInfo.tsx, src/pages/mypage/UserInfoFetcher.tsx, src/pages/overwatch/Card.tsx, src/pages/valorant/Card.tsx, src/pages/valorant/CreateCard.tsx, src/pages/valorant/EditCard.tsx, src/pages/valorant/MemberSlot.tsx, src/store/mypage-slice.ts, src/types/games.ts
=> [deploy] Update backgroundColor

src/apis/api/common.ts
=> [deploy] Add CardFinish message

src/pages/mypage/Games/AddGame.tsx, src/pages/mypage/Games/Nickname.tsx, src/pages/mypage/Games/ValorantInfo.tsx
=> [deploy] add valorant info to mypage

src/apis/api/valorant.ts, src/components/Review.tsx, src/pages/valorant/EmptySlot.tsx
=> [deploy] modify add party member function

src/pages/mypage/Games/LolInfo.tsx, src/pages/mypage/Games/Nickname.tsx, src/pages/mypage/Games/PubgInfo.tsx, src/pages/mypage/UserInfoFetcher.tsx
- fix user's game information update
=> fix user's game information update

src/apis/api/valorant.ts, src/components/Review.tsx, src/pages/valorant/EmptySlot.tsx
fix user's game information update err
=> [deploy] fix user's game information update err
